//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Packages/com.ab.fwp.inputeer/Runtime/Mapping/XboxMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @XboxMapping : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @XboxMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""XboxMapping"",
    ""maps"": [
        {
            ""name"": ""controller"",
            ""id"": ""9564b9d6-d0c2-414e-a4f2-1df7eb25e583"",
            ""actions"": [
                {
                    ""name"": ""joyLeft"",
                    ""type"": ""Value"",
                    ""id"": ""cbc0fe81-6f35-452f-a971-e931279d5959"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""joyRight"",
                    ""type"": ""Value"",
                    ""id"": ""b1572341-45f0-4c77-aa0f-16c245700a5f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""bumperL"",
                    ""type"": ""Value"",
                    ""id"": ""a89d9fcb-601e-42b4-9900-5961d8820f78"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""bumperR"",
                    ""type"": ""Value"",
                    ""id"": ""f7f7d8ec-ff6c-424f-a92f-281ba7ffad27"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""buttonSouth"",
                    ""type"": ""Button"",
                    ""id"": ""a7555927-57bd-4bc1-9b34-a162ef542a87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonWest"",
                    ""type"": ""Button"",
                    ""id"": ""2269dfac-9a49-4b00-aff6-4ee1e31913ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""4246a405-9c68-4897-b6f3-2bb01c80cf84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonEast"",
                    ""type"": ""Button"",
                    ""id"": ""e1ebd040-3a57-4b9a-aa30-4c650c50b4b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dPadSouth"",
                    ""type"": ""Button"",
                    ""id"": ""2b1e3d69-de51-4a49-a6bf-795351bf6398"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dPadNorth"",
                    ""type"": ""Button"",
                    ""id"": ""c704a55a-71cc-401c-9119-611a6ef3ca47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dPadWest"",
                    ""type"": ""Button"",
                    ""id"": ""8cdeaf69-1448-4579-aae1-505d3afee71c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dPadEast"",
                    ""type"": ""Button"",
                    ""id"": ""4e4ba8d9-ecab-49fb-b991-670ebeab1607"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonStart"",
                    ""type"": ""Button"",
                    ""id"": ""bc4c282f-7043-477d-9ac9-c2d5f4cac893"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pause"",
                    ""type"": ""Button"",
                    ""id"": ""99ab7c85-83cd-4f0f-a576-e4702e9fb7d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""triggerL"",
                    ""type"": ""Value"",
                    ""id"": ""3ae51194-af77-4d28-b206-2c3147a58989"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""triggerR"",
                    ""type"": ""Value"",
                    ""id"": ""af67a609-651d-497f-8198-763bd8711ed3"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""keyboard_arrows"",
                    ""id"": ""98c4deb3-8308-4dcb-9cd0-d20fd076c8bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""057f6649-e1b3-4ee9-a66e-5dd412217927"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7577b5fc-8c32-4d01-860c-582668c9725c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""241856ef-af93-48d5-ad9b-4b1afaf4e680"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a2bf1e1f-b045-4b5b-996e-f9f1a3412195"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""keyboard_ZQSD"",
                    ""id"": ""5b0be1b0-5e47-48e1-bb96-2559c3455c98"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""deb2b5d1-f97c-4067-b7de-0455216fb201"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""adb3c977-1cf2-4abe-9370-d8f5892d26fc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2c7f459d-941b-4ae6-b10f-f3371bc3e985"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7513d5f4-a6e2-49ca-8836-ac96f52f487e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""96e28e5f-663a-4487-9179-bb3e25556f22"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15b4fdcb-a5fb-4abc-a27e-afa735974a59"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35f12491-f43d-4021-866b-2179b63352a3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661968ca-d8e8-4714-b725-002db2e49765"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3db5095-7b81-4045-a9f9-284829354b01"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""124b1ef1-4afc-4fc5-847c-f51ec67b7e37"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8af5c726-a143-4268-b356-356dc9286f6a"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""692399aa-487f-444f-97de-e9bfe76ea420"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0043136-8ecb-4f48-9b08-4477176f0837"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""042eef1b-129c-4113-89b2-d3f3ee6b5cd8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dfc8e87-7492-4ed8-96e7-bc887c71f455"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8cc3b6a-41d7-418a-b37e-6845af519e4b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52244d18-1846-4308-a9ac-5099f9ccf280"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dPadEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9489789c-f4a7-4c40-b05b-83472a98cf9b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba7d93b9-74cb-4445-afb0-b7c50b4a4b34"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bba32e1b-6adc-4b77-8cf8-e4fba07d1640"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66dee08c-a089-4cb1-8828-4752e38a6012"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""keyboard_TFGH"",
                    ""id"": ""f0032c85-f147-4242-9844-bb340f28a646"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""65f5558d-7c67-40c5-9a61-06c5b64f97ba"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""65b8b735-003f-4236-beaf-caaf9e1a6358"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""389be45c-a382-47c6-9c88-ff0c55b8e271"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97273297-e9b4-4fcb-be15-e596ea11e886"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b0bad67c-5645-4815-a695-a32e63c4e143"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joyRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cb6d512-2a55-4b0e-b61f-f9688316612e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8626f3a8-7ceb-4e01-ae25-812d8de04bc4"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aaa10c5-fb96-43f3-96b2-127b0cea68d3"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1b807f3-4341-4bc8-8a8c-a2324d759056"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48293e40-ca4b-41fb-988a-2d58e9688b37"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""920acdc1-0ad5-4edc-b07a-e52b56876877"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b351ca1-01e9-4f79-a266-198117d6bbef"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b49bfcb-62fc-4537-9f6b-64d997ab9efc"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab02e05c-0e6e-4cfe-84a8-e51aae39234c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""786eaad4-408e-4fc9-8aaf-1d61fa48a380"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // controller
        m_controller = asset.FindActionMap("controller", throwIfNotFound: true);
        m_controller_joyLeft = m_controller.FindAction("joyLeft", throwIfNotFound: true);
        m_controller_joyRight = m_controller.FindAction("joyRight", throwIfNotFound: true);
        m_controller_bumperL = m_controller.FindAction("bumperL", throwIfNotFound: true);
        m_controller_bumperR = m_controller.FindAction("bumperR", throwIfNotFound: true);
        m_controller_buttonSouth = m_controller.FindAction("buttonSouth", throwIfNotFound: true);
        m_controller_buttonWest = m_controller.FindAction("buttonWest", throwIfNotFound: true);
        m_controller_buttonNorth = m_controller.FindAction("buttonNorth", throwIfNotFound: true);
        m_controller_buttonEast = m_controller.FindAction("buttonEast", throwIfNotFound: true);
        m_controller_dPadSouth = m_controller.FindAction("dPadSouth", throwIfNotFound: true);
        m_controller_dPadNorth = m_controller.FindAction("dPadNorth", throwIfNotFound: true);
        m_controller_dPadWest = m_controller.FindAction("dPadWest", throwIfNotFound: true);
        m_controller_dPadEast = m_controller.FindAction("dPadEast", throwIfNotFound: true);
        m_controller_buttonStart = m_controller.FindAction("buttonStart", throwIfNotFound: true);
        m_controller_pause = m_controller.FindAction("pause", throwIfNotFound: true);
        m_controller_triggerL = m_controller.FindAction("triggerL", throwIfNotFound: true);
        m_controller_triggerR = m_controller.FindAction("triggerR", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // controller
    private readonly InputActionMap m_controller;
    private IControllerActions m_ControllerActionsCallbackInterface;
    private readonly InputAction m_controller_joyLeft;
    private readonly InputAction m_controller_joyRight;
    private readonly InputAction m_controller_bumperL;
    private readonly InputAction m_controller_bumperR;
    private readonly InputAction m_controller_buttonSouth;
    private readonly InputAction m_controller_buttonWest;
    private readonly InputAction m_controller_buttonNorth;
    private readonly InputAction m_controller_buttonEast;
    private readonly InputAction m_controller_dPadSouth;
    private readonly InputAction m_controller_dPadNorth;
    private readonly InputAction m_controller_dPadWest;
    private readonly InputAction m_controller_dPadEast;
    private readonly InputAction m_controller_buttonStart;
    private readonly InputAction m_controller_pause;
    private readonly InputAction m_controller_triggerL;
    private readonly InputAction m_controller_triggerR;
    public struct ControllerActions
    {
        private @XboxMapping m_Wrapper;
        public ControllerActions(@XboxMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @joyLeft => m_Wrapper.m_controller_joyLeft;
        public InputAction @joyRight => m_Wrapper.m_controller_joyRight;
        public InputAction @bumperL => m_Wrapper.m_controller_bumperL;
        public InputAction @bumperR => m_Wrapper.m_controller_bumperR;
        public InputAction @buttonSouth => m_Wrapper.m_controller_buttonSouth;
        public InputAction @buttonWest => m_Wrapper.m_controller_buttonWest;
        public InputAction @buttonNorth => m_Wrapper.m_controller_buttonNorth;
        public InputAction @buttonEast => m_Wrapper.m_controller_buttonEast;
        public InputAction @dPadSouth => m_Wrapper.m_controller_dPadSouth;
        public InputAction @dPadNorth => m_Wrapper.m_controller_dPadNorth;
        public InputAction @dPadWest => m_Wrapper.m_controller_dPadWest;
        public InputAction @dPadEast => m_Wrapper.m_controller_dPadEast;
        public InputAction @buttonStart => m_Wrapper.m_controller_buttonStart;
        public InputAction @pause => m_Wrapper.m_controller_pause;
        public InputAction @triggerL => m_Wrapper.m_controller_triggerL;
        public InputAction @triggerR => m_Wrapper.m_controller_triggerR;
        public InputActionMap Get() { return m_Wrapper.m_controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void SetCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterface != null)
            {
                @joyLeft.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyLeft;
                @joyLeft.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyLeft;
                @joyLeft.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyLeft;
                @joyRight.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyRight;
                @joyRight.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyRight;
                @joyRight.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnJoyRight;
                @bumperL.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperL;
                @bumperL.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperL;
                @bumperL.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperL;
                @bumperR.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperR;
                @bumperR.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperR;
                @bumperR.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnBumperR;
                @buttonSouth.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonSouth;
                @buttonSouth.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonSouth;
                @buttonSouth.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonSouth;
                @buttonWest.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonWest;
                @buttonWest.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonWest;
                @buttonWest.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonWest;
                @buttonNorth.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonNorth;
                @buttonNorth.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonNorth;
                @buttonNorth.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonNorth;
                @buttonEast.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonEast;
                @buttonEast.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonEast;
                @buttonEast.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonEast;
                @dPadSouth.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadSouth;
                @dPadSouth.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadSouth;
                @dPadSouth.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadSouth;
                @dPadNorth.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadNorth;
                @dPadNorth.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadNorth;
                @dPadNorth.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadNorth;
                @dPadWest.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadWest;
                @dPadWest.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadWest;
                @dPadWest.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadWest;
                @dPadEast.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadEast;
                @dPadEast.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadEast;
                @dPadEast.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDPadEast;
                @buttonStart.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonStart;
                @buttonStart.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonStart;
                @buttonStart.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButtonStart;
                @pause.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnPause;
                @pause.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnPause;
                @pause.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnPause;
                @triggerL.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerL;
                @triggerL.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerL;
                @triggerL.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerL;
                @triggerR.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerR;
                @triggerR.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerR;
                @triggerR.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerR;
            }
            m_Wrapper.m_ControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @joyLeft.started += instance.OnJoyLeft;
                @joyLeft.performed += instance.OnJoyLeft;
                @joyLeft.canceled += instance.OnJoyLeft;
                @joyRight.started += instance.OnJoyRight;
                @joyRight.performed += instance.OnJoyRight;
                @joyRight.canceled += instance.OnJoyRight;
                @bumperL.started += instance.OnBumperL;
                @bumperL.performed += instance.OnBumperL;
                @bumperL.canceled += instance.OnBumperL;
                @bumperR.started += instance.OnBumperR;
                @bumperR.performed += instance.OnBumperR;
                @bumperR.canceled += instance.OnBumperR;
                @buttonSouth.started += instance.OnButtonSouth;
                @buttonSouth.performed += instance.OnButtonSouth;
                @buttonSouth.canceled += instance.OnButtonSouth;
                @buttonWest.started += instance.OnButtonWest;
                @buttonWest.performed += instance.OnButtonWest;
                @buttonWest.canceled += instance.OnButtonWest;
                @buttonNorth.started += instance.OnButtonNorth;
                @buttonNorth.performed += instance.OnButtonNorth;
                @buttonNorth.canceled += instance.OnButtonNorth;
                @buttonEast.started += instance.OnButtonEast;
                @buttonEast.performed += instance.OnButtonEast;
                @buttonEast.canceled += instance.OnButtonEast;
                @dPadSouth.started += instance.OnDPadSouth;
                @dPadSouth.performed += instance.OnDPadSouth;
                @dPadSouth.canceled += instance.OnDPadSouth;
                @dPadNorth.started += instance.OnDPadNorth;
                @dPadNorth.performed += instance.OnDPadNorth;
                @dPadNorth.canceled += instance.OnDPadNorth;
                @dPadWest.started += instance.OnDPadWest;
                @dPadWest.performed += instance.OnDPadWest;
                @dPadWest.canceled += instance.OnDPadWest;
                @dPadEast.started += instance.OnDPadEast;
                @dPadEast.performed += instance.OnDPadEast;
                @dPadEast.canceled += instance.OnDPadEast;
                @buttonStart.started += instance.OnButtonStart;
                @buttonStart.performed += instance.OnButtonStart;
                @buttonStart.canceled += instance.OnButtonStart;
                @pause.started += instance.OnPause;
                @pause.performed += instance.OnPause;
                @pause.canceled += instance.OnPause;
                @triggerL.started += instance.OnTriggerL;
                @triggerL.performed += instance.OnTriggerL;
                @triggerL.canceled += instance.OnTriggerL;
                @triggerR.started += instance.OnTriggerR;
                @triggerR.performed += instance.OnTriggerR;
                @triggerR.canceled += instance.OnTriggerR;
            }
        }
    }
    public ControllerActions @controller => new ControllerActions(this);
    public interface IControllerActions
    {
        void OnJoyLeft(InputAction.CallbackContext context);
        void OnJoyRight(InputAction.CallbackContext context);
        void OnBumperL(InputAction.CallbackContext context);
        void OnBumperR(InputAction.CallbackContext context);
        void OnButtonSouth(InputAction.CallbackContext context);
        void OnButtonWest(InputAction.CallbackContext context);
        void OnButtonNorth(InputAction.CallbackContext context);
        void OnButtonEast(InputAction.CallbackContext context);
        void OnDPadSouth(InputAction.CallbackContext context);
        void OnDPadNorth(InputAction.CallbackContext context);
        void OnDPadWest(InputAction.CallbackContext context);
        void OnDPadEast(InputAction.CallbackContext context);
        void OnButtonStart(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnTriggerL(InputAction.CallbackContext context);
        void OnTriggerR(InputAction.CallbackContext context);
    }
}
